package com.ibm.academia.restapi.tarjeta.enumeradores;

public enum TipoTarjeta {
	B_SMART,
	AFINITY_CARD,
	CLASICA,
	OFFICE_DEPOT,
	COSTCO,
	BEST_BUY,
	BANAMEX,
	THE_HOME_DEPOT,
	ORO,
	PLATINIUM,
	CITI_AADVANTAGE,
	TELETON,
	APAC,
	MARTI_CLASICA_CITIBANAMEX,
	AMERICA_DEPORTEISMO,
	PUMAS_DEPORTEISMO,
	TOLUCA_DEPORTEISMO,
	LA_VERDE_DEPORTEISMO,
	MARTI_PREMIUM_CITIBANAMEX
}
